# -*- coding: utf-8 -*-
"""FinalDeep.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XVNxR5S4LVVh64sV8SKJGW_eGcnOkLCG

SECCIÓN 1 — Instalación de dependencias
"""

!pip install librosa gdown soundfile tensorflow_hub

"""SECCIÓN 2 — Importaciones y Configuración del Dataset"""

import numpy as np
import librosa
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import tensorflow_hub as hub
import soundfile as sf
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.utils import to_categorical
import gdown
import zipfile

"""SECCIÓN 3 — Descarga y extracción del Dataset
📌 Se organiza automáticamente en carpetas por género
"""

# ID del archivo GTZAN en tu Google Drive
file_id = "1XP20Z-T-Q_7uvyXjPS7-aIxW_8XRhYo9"
url = f"https://drive.google.com/uc?id={file_id}"

output_zip = "/content/genres.zip"

print("📥 Descargando dataset...")
gdown.download(url, output_zip, quiet=False)

print("📂 Extrayendo...")
with zipfile.ZipFile(output_zip, 'r') as zip_ref:
    zip_ref.extractall('/content/')

DATA_PATH = "/content/genres"

GENRES = ['blues','classical','country','disco','hiphop',
          'jazz','metal','pop','reggae','rock']

"""SECCIÓN 4 — Modelo YAMNet para extraer embeddings

📌 Convierte audio → vector 1024 dimensiones
"""

yamnet = hub.load('https://tfhub.dev/google/yamnet/1')

def extract_yamnet_embeddings(file_path):
    try:
        audio, sr = sf.read(file_path, dtype='float32')

        if sr != 16000:
            audio = librosa.resample(audio, orig_sr=sr, target_sr=16000)

        _, embeddings, _ = yamnet(audio)
        return np.mean(embeddings.numpy(), axis=0)

    except Exception as e:
        print("Error:", e)
        return None

"""SECCIÓN 5 — Carga del dataset y extracción de embeddings"""

print("🎧 Extrayendo embeddings...")

features = []
labels = []

for genre in GENRES:
    folder = os.path.join(DATA_PATH, genre)
    files = [f for f in os.listdir(folder) if f.endswith(".au")]

    for f in files:
        fp = os.path.join(folder, f)
        emb = extract_yamnet_embeddings(fp)

        if emb is not None:
            features.append(emb)
            labels.append(genre)

X = np.array(features)
y = np.array(labels)

print("✔ Listo!")
print("X shape:", X.shape)
print("Samples:", len(y))

"""SECCIÓN 6 — Codificación y División Train/Test"""

label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)
y_cat = to_categorical(y_encoded)

X_train, X_test, y_train, y_test = train_test_split(
    X, y_cat, test_size=0.2, random_state=42, stratify=y_encoded
)

print("📊 Train:", X_train.shape, "| Test:", X_test.shape)

"""SECCIÓN 7 — Modelo de Clasificación

📌 Entrada: 1024 features → Salida: 10 géneros
"""

model = Sequential([
    Dense(512, activation='relu', input_shape=(1024,)),
    Dropout(0.3),
    Dense(256, activation='relu'),
    Dropout(0.3),
    Dense(len(GENRES), activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy',
              metrics=['accuracy'])

model.summary()

"""SECCIÓN 8 — Entrenamiento del modelo"""

history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=40,
    batch_size=32,
    verbose=1
)

"""SECCIÓN 9 — Evaluación"""

loss, acc = model.evaluate(X_test, y_test, verbose=0)
print(f"\n🎯 Accuracy en test: {acc*100:.2f}%")

"""SECCIÓN 10 — Predicción desde audio real + Reproductor"""

import ipywidgets as widgets
from IPython.display import Audio, display, clear_output
import random

def test_random_audio(_=None):
    clear_output(wait=True)
    print("🎲 Seleccionando audio aleatorio...")

    genre = random.choice(GENRES)
    folder = os.path.join(DATA_PATH, genre)
    files = [f for f in os.listdir(folder) if f.endswith(".au")]

    file = random.choice(files)
    fp = os.path.join(folder, file)

    print(f"\n🗂 Archivo: {file}")
    print(f"🎵 Género real: {genre}")

    # Reproducir audio
    audio, sr = librosa.load(fp, sr=None)
    display(Audio(audio, rate=sr))

    emb = extract_yamnet_embeddings(fp)
    emb = emb.reshape(1, -1)

    pred = model.predict(emb, verbose=0)[0]
    idx = np.argmax(pred)
    pred_genre = label_encoder.inverse_transform([idx])[0]

    print(f"\n🔮 Predicción: {pred_genre}")
    print("-----------------------------------")

    button = widgets.Button(description="▶ Otro audio", button_style="success")
    button.on_click(test_random_audio)
    display(button)

test_random_audio()